# Working with images

### importing the necessary modules

In [1]:
import cv2
import numpy as np


### Loading an image from file

In [2]:
img = cv2.imread('images/opencv-logo.png', cv2.IMREAD_GRAYSCALE)

Second argument is a flag which specifies the way image should be read.

* cv2.IMREAD_COLOR : Loads a color image. Any transparency of image will be neglected. It is the default flag.
* cv2.IMREAD_GRAYSCALE : Loads image in grayscale mode
* cv2.IMREAD_UNCHANGED : Loads image as such including alpha channel

### displaying the image

In [3]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### but what is the image itself

In [4]:
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
type(img)

numpy.ndarray

In [6]:
width, height = img.shape[:2]
print("width = {}".format(width))
print("height = {}".format(height))

width = 99
height = 82


Please note that {img.shape} will hold an array of 3 when the image is in color the third number is the channels

### saving an image

In [7]:
cv2.imwrite('test.png',img)

True

## Color spaces (modes)

OpenCV supports several color spaces
* RGB   - Red Green Blue
* LAB   - L: Lightness (Intensity), A: ranging from Green to Magenta, B: ranging from Blue to Yellow  
* HSV   - Hue (Dominant Wavelength), Saturation(Purity / shades of the color), Value(Intensity)
* YCrCb - ...

### RGB (OpenCV uses BGR)

* comprised of three 8 bit triplet (e.g. (10, 20, 30) 
* each color holds 256 possiblities

QUESTION - How many different colors can be produces from this color scheme ?

#### RGB color table


![title](images/rgb-color-table.png)

To read more on the other color spaces take a look at  https://www.learnopencv.com/color-spaces-in-opencv-cpp-python/

## How to access a single pixel

### Standard coordinate system (cartesian)

![title](images/cartesian_coordinates.png)

coordinates are specified in (x, y)

### coordinate system used in images

![title](images/image_coordinates.png)

coordinates are specified in (y, x)

## Drawing on images

### First lets create a blank image

In [8]:
import cv2
import numpy as np

image = np.zeros((512,512,3), np.uint8)

In [9]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a line

Draw a diagonal blue line with thickness of 5 px

In [10]:
image = cv2.line(image,(0,0),(511,511),(255,0,0), 1)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a rectangle

To draw a rectangle, you need top-left corner and bottom-right corner of rectangle. This time we will draw a green rectangle at the top-right corner of image.

In [11]:
image = cv2.rectangle(image,(384,0),(510,128),(0,255,0),3)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a circle

To draw a circle, you need its center coordinates and radius. We will draw a circle inside the rectangle drawn above.<BR>
please note that the last parameter below is the line thickness , when a -1 ig given the rectangle is filled with color.

In [12]:
image = cv2.circle(image,(447,63), 63, (0,0,255), -1)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing Ellipse

To draw the ellipse, we need to pass several arguments.
* The center location (x,y). 
* Axes lengths (major axis length, minor axis length). 
* Angle is the angle of rotation of ellipse in anti-clockwise direction. 
* StartAngle 
* EndAngle (denotes the starting and ending of ellipse arc measured in clockwise direction from major axis. i.e. giving values 0 and 360 gives the full ellipse. 
* Color (a tupple of 3 can be given) or a single uint8 (= blue)
* Thickness (-1 = fill)

For more details, check the documentation of cv2.ellipse(). Below example draws a half ellipse at the center of the image.

In [13]:
image = cv2.ellipse(image,(256,256),(100,50),0,0,180,(255,255,255),1)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a polygon

To draw a polygon, first you need coordinates of vertices. Make those points into an array of shape ROWSx1x2 where ROWS are number of vertices and it should be of type int32. Here we draw a small polygon of with four vertices in yellow color.

In [14]:
pts = np.array([[100,10],[200,20],[180,100],[80,50]], np.int32)
pts = pts.reshape((-1,1,2))
image = cv2.polylines(image,[pts],True,(0,255,255))
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Note:
* If third argument (in cv2.polylines(..)) is False, you will get a polylines joining all the points, not a closed shape.
* cv2.polylines() can be used to draw multiple lines. Just create a list of all the lines you want to draw and pass it to the function. All lines will be drawn individually. It is more better and faster way to draw a group of lines than calling cv2.line() for each line.

### Adding Text to Images:

#### To put texts in images, you need specify following things
* Text data that you want to write
* Position coordinates of where you want put it (i.e. bottom-left corner where data starts).
* Font type (Check cv2.putText() docs for supported fonts)
* Font Scale (specifies the size of font)
* color
* thickness, 
* lineType (lineType = cv2.LINE_AA is recommended)



In [15]:
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(image,'OpenCV',(10,500), font, 4,(255,255,255),2,cv2.LINE_AA)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## More on image file formats

Discussion on Image file formats can be found at https://mmeysenburg.github.io/image-processing/02-image-basics/

### ASSIGNMENT

create a simple animation using only the above API you have learned.
The animation should last at least 